{
 "title": "Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Vote Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"default-vote-vote@kubernetes\", code=\"200\"}[$__interval]))",
     "legendFormat": "Total Vote Requests"
    }
   ]
  },
  {
   "title": "Total Result Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"default-result-result@kubernetes\", code=\"200\"}[$__interval]))",
     "legendFormat": "Total Results Requests"
    }
   ]
  },
  {
   "title": "Average Response Time (ms)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "(sum(traefik_service_request_duration_seconds_sum{service=\"default-vote-vote@kubernetes\", code=\"200\"}) * 1000) / sum(traefik_service_requests_total{service=\"default-vote-vote@kubernetes\", code=\"200\"})",
     "legendFormat": "Vote Service Response Time in ms"
    },
    {
     "expr": "(sum(traefik_service_request_duration_seconds_sum{service=\"default-result-result@kubernetes\", code=\"200\"}) * 1000) / sum(traefik_service_requests_total{service=\"default-result-result@kubernetes\", code=\"200\"})",
     "legendFormat": "Result Service Response Time in ms"
    }
   ]
  }
 ]
}