apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qtedgeautoscalers.dackk.lancaster.ac.uk
spec:
  scope: Namespaced
  group: dackk.lancaster.ac.uk
  names:
    kind: QTEdgeAutoscaler
    plural: qtedgeautoscalers
    singular: qtedgeautoscaler
    shortNames:
      - qteas
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
